# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=news.models.upload_location, width_field='width_field'),
        ),
    ]
